version: '3.4'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SQL=Server=sqlserver; Database=identity-db; User Id=sa;Password=8jkGh47hnDw89Haq8LN2;Persist Security Info=False;Encrypt=False
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "2589:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  message.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SQL=Server=sqlserver; Database=message-db; User Id=sa;Password=8jkGh47hnDw89Haq8LN2;Persist Security Info=False;Encrypt=False
      - ASPNETCORE_URLS=http://+:80
      - URLS__Identity=http://identity.api:9632
    ports:
      - "2590:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  signal.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - URLS__Message=http://message.api:9633
    ports:
      - "2591:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  tetherfi.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "2592:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # tetherfi.web:
  #   ports:
  #     - "4200:4200"
